<?php

namespace AppBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $dateVisit
     */
    public function countTicketSold($dateVisit)
    {
        $queryBuilder = $this->createQueryBuilder('r');
        $queryBuilder
            ->select('count(r.nbTicket)')
            ->where('r.dateVisit=:dateVisit');

        return $queryBuilder->getQuery()->getScalarResult();

    }
}
