<?php

namespace AppBundle\Repository;
/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $dateVisit
     * @return
     */
    public function countTicketSold($dateVisit)
    {
        // on recupere le querybuilder en utilisant la methode createQueryBuilder() avec l'alias en argument(=raccourci de l'entity)
        $queryBuilder = $this->createQueryBuilder('r');
         $queryBuilder                         // on utilise les methodes du querybuilder pour construire notre requete
            ->select('count(r.nbTicket)')
            ->where('r.dateVisit=:dateVisit')
            ->setParameter('dateVisit', $dateVisit);

         return $queryBuilder->getQuery()->getSingleScalarResult();


    }
}
