booking_homepage:
    path:     /
    defaults: { _controller: AppBundle:Booking:index }

booking_organisation:
    path:    /organisation
    defaults: { _controller: AppBundle:Booking:organize }

booking_identification:
    path:    /identification
    defaults: { _controller: AppBundle:Booking:identification }

booking_payment:
    path:    /payment
    defaults: { _controller: AppBundle:Booking:payment }