# Home
booking_home:
    path:    /
    defaults: { _controller: AppBundle:Booking:index }

# Visit organisation
booking_organisation:
    path:    /organisation
    defaults: { _controller: AppBundle:Booking:organize }

# identification visitors
booking_identification:
    path:    /identification
    defaults: { _controller: AppBundle:Booking:identification }

# payment
booking_payment:
    path:    /payment
    defaults: { _controller: AppBundle:Booking:payment }