<<<<<<< HEAD
booking_homepage:
    path:     /
    defaults: { _controller: AppBundle:Booking:index }

=======
# Home
booking_home:
    path:    /
    defaults: { _controller: AppBundle:Booking:index }

# Visit organisation
>>>>>>> test
booking_organisation:
    path:    /organisation
    defaults: { _controller: AppBundle:Booking:organize }

<<<<<<< HEAD
=======
# identification visitors
>>>>>>> test
booking_identification:
    path:    /identification
    defaults: { _controller: AppBundle:Booking:identification }

<<<<<<< HEAD
=======
# payment
>>>>>>> test
booking_payment:
    path:    /payment
    defaults: { _controller: AppBundle:Booking:payment }