services:
    app.InvalidBookingDate:
        class: AppBundle\Services\InvalidBookingDate

    app.MaxTicketSold:
        class: AppBundle\Services\MaxTicketSold
        arguments: ["@doctrine.orm.entity_manager"]

    app.GenerateTicket:
        class: AppBundle\Services\GenerateTicket
        arguments: ["@doctrine.orm.entity_manager"]

    app.ValidateDate:
        class: AppBundle\Services\ValidateDate
        arguments: ["@app.InvalidBookingDate"]

    app.HalfDay:
        class: AppBundle\Services\HalfDay

    app.PriceCalculator:
        class: AppBundle\Services\PriceCalculator

    app.GenerateToken:
        class: AppBundle\Services\GenerateToken

    app.SendEmail:
        class: AppBundle\Services\SendEmail
        arguments: ["@Swift_Mailer"]

    app.PayWithStripe:
        class: AppBundle\Services\PayWithStripe
